# Generated by Django 5.2.7 on 2025-11-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillgraph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('skills', models.JSONField()),
                ('median_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(max_length=32)),
                ('notifications_enabled', models.BooleanField()),
                ('years_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'accounts_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountsWorkexperience',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('skills', models.JSONField()),
                ('median_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(max_length=32)),
                ('order', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'accounts_workexperience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChatbotChathistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('tool_used', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField()),
                ('response_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chatbot_chathistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StackoverflowDataCleaned2025',
            fields=[
                ('response_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ed_level', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('work_exp', models.TextField(blank=True, null=True)),
                ('comp', models.TextField(blank=True, null=True)),
                ('language_have', models.TextField(blank=True, null=True)),
                ('language_want', models.TextField(blank=True, null=True)),
                ('database_have', models.TextField(blank=True, null=True)),
                ('database_want', models.TextField(blank=True, null=True)),
                ('platform_have', models.TextField(blank=True, null=True)),
                ('platform_want', models.TextField(blank=True, null=True)),
                ('webframe_have', models.TextField(blank=True, null=True)),
                ('webframe_want', models.TextField(blank=True, null=True)),
                ('devenvs_have', models.TextField(blank=True, null=True)),
                ('devenvs_want', models.TextField(blank=True, null=True)),
                ('job_sat', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stackoverflow_data_cleaned_2025',
                'db_table_comment': 'newest version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StackoverflowDataCleanedMultiYear',
            fields=[
                ('response_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('ed_level', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('work_exp', models.TextField(blank=True, null=True)),
                ('comp', models.TextField(blank=True, null=True)),
                ('language_have', models.TextField(blank=True, null=True)),
                ('language_want', models.TextField(blank=True, null=True)),
                ('database_have', models.TextField(blank=True, null=True)),
                ('database_want', models.TextField(blank=True, null=True)),
                ('platform_have', models.TextField(blank=True, null=True)),
                ('platform_want', models.TextField(blank=True, null=True)),
                ('webframe_have', models.TextField(blank=True, null=True)),
                ('webframe_want', models.TextField(blank=True, null=True)),
                ('job_sat', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stackoverflow_data_cleaned_multi_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StackoverflowDataCleanedMultiYearExploded',
            fields=[
                ('response_id', models.BigIntegerField(blank=True, null=True)),
                ('year', models.BigIntegerField(blank=True, null=True)),
                ('ed_level', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('role', models.TextField(blank=True, null=True)),
                ('work_exp', models.TextField(blank=True, null=True)),
                ('comp', models.TextField(blank=True, null=True)),
                ('language_have', models.TextField(blank=True, null=True)),
                ('language_want', models.TextField(blank=True, null=True)),
                ('database_have', models.TextField(blank=True, null=True)),
                ('database_want', models.TextField(blank=True, null=True)),
                ('platform_have', models.TextField(blank=True, null=True)),
                ('platform_want', models.TextField(blank=True, null=True)),
                ('webframe_have', models.TextField(blank=True, null=True)),
                ('webframe_want', models.TextField(blank=True, null=True)),
                ('job_sat', models.TextField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'stackoverflow_data_cleaned_multi_year_exploded',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='SurveyResultsPublic2025',
        ),
    ]
