# Generated by Django 5.2.7 on 2025-11-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCourses',
            fields=[
                ('source', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('level', models.TextField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
                ('description_full', models.TextField(blank=True, null=True)),
                ('url', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'all_courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CodecademyRaw',
            fields=[
                ('title', models.TextField(blank=True, null=True)),
                ('level', models.TextField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
                ('description_full', models.TextField(blank=True, null=True)),
                ('url', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'codecademy_raw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseraRaw',
            fields=[
                ('keyword', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('partner', models.TextField(blank=True, null=True)),
                ('level', models.TextField(blank=True, null=True)),
                ('rating', models.TextField(blank=True, null=True)),
                ('rating_count', models.TextField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
                ('what_you_will_learn', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('recommended_experience', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'coursera_raw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatacampRaw',
            fields=[
                ('title', models.TextField(blank=True, null=True)),
                ('level', models.TextField(blank=True, null=True)),
                ('duration', models.TextField(blank=True, null=True)),
                ('description_full', models.TextField(blank=True, null=True)),
                ('url', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'datacamp_raw',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LangchainPgCollection',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True)),
                ('cmetadata', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'langchain_pg_collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LangchainPgEmbedding',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('embedding', models.TextField(blank=True, null=True)),
                ('document', models.CharField(blank=True, null=True)),
                ('cmetadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'langchain_pg_embedding',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StackoverflowJobs2025',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('job', models.TextField(blank=True, null=True)),
                ('top_language', models.JSONField(blank=True, null=True)),
                ('top_database', models.JSONField(blank=True, null=True)),
                ('top_platform', models.JSONField(blank=True, null=True)),
                ('top_framework', models.JSONField(blank=True, null=True)),
                ('work_exp', models.FloatField(blank=True, null=True)),
                ('yearly_comp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stackoverflow_jobs_2025',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyResultsPublic2025',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'survey_results_public_2025',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('job_title', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('median_salary', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('work_experiences', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('notifications_enabled', models.BooleanField(blank=True, null=True)),
                ('job_transitions', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
